---
- name: Pull Docker Image of calculator
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull Image
      docker_image:
        name: prudhveee/calculator:latest
        source: pull
    - name: Start Docker Service
      service:
        name: docker
        state: started
    - name: Run Container
      command: docker run -it -d --name calculator prudhveee/calculator
